### ISSUE TITLE
wrong constant for epoch seconds

### ISSUE THREAD

**Issue by skilchen** [Skrylar/rfc3339#1]
first of all: thanks for this nice library!
i enjoyed playing with it and i found some issues ...
the first of them is: 
you use a wrong constant for the seconds of the epoch date. you use: 62167219200
(which is 1971-01-01T00:00:00Z, according to pythons fromordinal) instead of 62135683200 (for 1970-01-01T00:00:00Z)
You probably should define a EpochSeconds for this instead of repeating the numerical value in to_epoch and to_epoch_date

**Comment by skilchen** [comment]
sorry, i could be wrong in this issue. i am no longer sure that my interpretation that there is no year 0 is correct especially in the context of rfc3339. the abnf grammar seems to allow a year 0.

**Comment by Skrylar** [comment]
RFC 3339 does indeed allow a year zero, according to the grammar.

> date-fullyear   = 4DIGIT
> date-month      = 2DIGIT  ; 01-12
> date-mday       = 2DIGIT  ; 01-28, 01-29, 01-30, 01-31 based on month/year
> -- https://tools.ietf.org/html/rfc3339#section-5

Yet this time period does not seem to exist (I only found references to 0001 at the time of writing):

> Year zero does not exist in the Anno Domini system usually used to number years in the Gregorian calendar and in its predecessor, the Julian calendar. In this system, the year 1 BC is followed by AD 1. However, there is a year zero in astronomical year numbering (where it coincides with the Julian year 1 BC) and in ISO 8601:2004 (where it coincides with the Gregorian year 1 BC) as well as in all Buddhist and Hindu calendars. --https://en.wikipedia.org/wiki/Year_zero

Unless there is an errata that clarifies we shouldn't allow it, I'm inclined to try and support it nonetheless. This might require more clarified documentation and a different converter to maintain interop with more "pragmatic" implementations others are using.

**Comment by Skrylar** [comment]
I think the best solution to this is for year zero to be a negative number, and year one being equal to zero. That satisfies the grammar requirement, is compatible with the other standard having a 1 B.C. and should be compatible with epoch time.

**Comment by Skrylar** [comment]
Should have been marked as #2 in the commit, but derping happened.

**Comment by Skrylar** [comment]
This is fixed now.
