### ISSUE TITLE
wrong interpretation of 'Z'

### ISSUE THREAD

**Issue by skilchen** [Skrylar/rfc3339#2]
You use 'Z' as a generic separator of the timezone data.
But as far as i understand rfc3339 'Z'  is a shortcut for 'UTC'
Numerical timezone offsets aren't separated by 'Z', instead the +hh:mm or -hh:mm are appended to the time-string without any separator.
```nim
import rfc3339
var x = "2017-09-08T01:02:03".to_date()
echo $x
```
produces:
```
0000-01-01T00:00:00Z+00:00
```
which is obviously completely wrong. But in this issue, only the "Z+00:00" is of interest.
The Z should not be there. And the +00:00 probably neither, because no timezone info is given in the string to parse.
The 'Z' should only be there if you know that you have a DateTime in UTC (with offset known to be set to 00:00).

**Comment by Skrylar** [comment]
>   time-secfrac    = "." 1*DIGIT
>   time-numoffset  = ("+" / "-") time-hour ":" time-minute
>   time-offset     = "Z" / time-numoffset
>
>   partial-time    = time-hour ":" time-minute ":" time-second [time-secfrac]
>   full-date       = date-fullyear "-" date-month "-" date-mday
>   full-time       = partial-time time-offset
>
>   date-time       = full-date "T" full-time
> -- https://tools.ietf.org/html/rfc3339#section-5.6

Having a time offset is technically not optional (though most parsers accept it, and I believe this one will _read_ such times for pragmatism) although the grammar does seem to read "Z" _or_ "some offset amount."

**Comment by Skrylar** [comment]
Fixed.
