### ISSUE TITLE
Interested in a `htmlParse` procedure for this library?

### ISSUE THREAD

**Issue by JohnAD** [Skrylar/rfc3339#7]
I'm in the process of writing a web framework in nim that glues over a dozen libraries together to make it possible to make a web site somewhat easier. It includes "jester", "moustachu", and other components. I'm also in the process of making videos and writing docs to cover it.

This is one of the libraries I'm using. AFAIK, nim's standard Time library has no ability to parse an HTML-formatted string, with it's subtle variations into a Time (or DateTime) object. Specifically, I'm talking about HTML5's `input type="date"`, `input type="datetime"`, and `input type="datetime-local"` formats. So, I'm using your excellent work instead.

Unfortunately, HTML5 implementations are slightly different than RFC3339 formatted strings. So I've written a wrapper for your `proc to_date*(self: string): DateTime`.

When I'm done, would you be interested in adding this procedure to your library?

About all I have left is getting my wrapper to handle timezone's properly. I need to adjust the return value of your `to_epoch` function to match up with nim's `Time` type for proper conversion. After that, the code should be ready.

**Comment by Skrylar** [comment]
I'll take a look at the wrapper, although it looks like I might have to compare the two date formats. Are you looking to parse the dates from the browser, or after they've been encoded in ISO-8601?

According to the W3C, HTML5 date/times are in an ISO format similar to but with a few niggles:

> It is therefore important to distinguish the time, date, and number formats used in HTML and in form submissions, which are always the formats defined in this specification (and based on the well-established **ISO 8601** standard for computer-readable date and time formats), from the time, date, and number formats presented to the user by the browser and accepted as input from the user by the browser.
> -- https://www.w3.org/TR/html52/sec-forms.html#date-time-and-number-formats

**Comment by JohnAD** [comment]
Getting the details right is key, I agree. The routine is:

* *not* handling the graphical localized datetime format shown on the browser screen, and
* *not* handling all possble parsable text dates accepted as text in a `date` or `datetime` field. (such as "`07-18`" for July 18.)

This is strictly a wrapper that takes the normalized return header request values from `date`, `datetime` (deprecated), and `datetime-local`, but not `time`. It would take that string (which is almost ISO-8601) and convert it to proper RFC-3339 form.  (Either as a string, or go straight to `rfc3339.DateTime` object.)

The challenges:

* Test with the common browsers to verify consistency.
* Handle all the odd combinations seen with useful defaults. For example, if the browser sends "`2018-07-18 12:34`" (no seconds), we still get our "`2018-07-18T12:34:00Z`"
   * (BTW, I'm not convinced zulu time is the best default. But you bring that up in #8 )

I should point out I'm not a time expert. I'm simply wanting to use this for the web framework library.

**Comment by Skrylar** [comment]
Will probably use this module as the base to write an ISO parser, since that format has come up again recently.
